#!/bin/bash

# This is a thin wrapper around exosis-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using exosis-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_EXOSISD

# Grab the value of $REAL_EXOSISCLI which may be exosis-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_EXOSISCLI}" "$@" | sed 's/\r//'
